# Generated by Django 5.2.8 on 2025-11-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_saham_stockupdatelog_stockdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='saham',
        ),
        migrations.DeleteModel(
            name='StockUpdateLog',
        ),
        migrations.AddField(
            model_name='saham',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saham',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saham',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saham',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saham',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saham',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
