# Generated by Django 5.2.8 on 2025-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_stockdata_saham_delete_stockupdatelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='last_fundamental_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
