# Generated by Django 5.2.8 on 2025-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_saham_last_fundamental_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
